<a href="https://colab.research.google.com/github/norman-AI-2025/data-science-norman/blob/main/week5tuto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [5]:
from google.colab import drive

In [6]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
df = pd.read_csv('/content/drive/MyDrive/dataset/salary (1).csv')

In [9]:
df.head()

,Unnamed: 0,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,0,2021-04-27 11:02:09.743,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,55000,0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,1,2021-04-27 11:02:21.562,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,54600,4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,2,2021-04-27 11:02:38.125,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,34000,NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,3,2021-04-27 11:02:40.643,25-34,Nonprofits,Program Manager,NaN,62000,3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4,2021-04-27 11:02:41.793,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,60000,7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28180 entries, 0 to 28179
Data columns (total 19 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   Unnamed: 0                                                                                                                                                                                                                            28180 non-null  int64
 1   Timestamp                                                                                                                                                                                                                             28180 non-null  object
 2   How old are you?                                                                                                                                                                                                                      28180 non-null  object
 3   What industry do you work in?                                                                                                                                                                                                         28099 non-null  object
 4   Job title                                                                                                                                                                                                                             28178 non-null  object
 5   If your job title needs additional context, please clarify here:                                                                                                                                                                      7284 non-null   object
 6   What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  28180 non-null  int64
 7   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                        20824 non-null  float64
 8   Please indicate the currency                                                                                                                                                                                                          28180 non-null  object
 9   If "Other," please indicate the currency here:                                                                                                                                                                                        217 non-null    object
 10  If your income needs additional context, please provide it here:                                                                                                                                                                      3050 non-null   object
 11  What country do you work in?                                                                                                                                                                                                          28180 non-null  object
 12  If you're in the U.S., what state do you work in?                                                                                                                                                                                     23124 non-null  object
 13  What city do you work in?                                                                                                                                                                                                             28098 non-null  object
 14  How many years of professional work experience do you have overall?                                                                                                                                                                   28180 non-null  object
 15  How many years of professional work experience do you have in your field?                                                                                                                                                             28180 non-null  object
 16  What is your highest level of education completed?                                                                                                                                                                                    27944 non-null  object
 17  What is your gender?                                                                                                                                                                                                                  27998 non-null  object
 18  What is your race? (Choose all that apply.)                                                                                                                                                                                           27990 non-null  object
dtypes: float64(1), int64(2), object(16)
memory usage: 4.1+ MB

In [12]:
df.isna().sum()

Unnamed: 0                                                                                                                                                                                                                                  0
Timestamp                                                                                                                                                                                                                                   0
How old are you?                                                                                                                                                                                                                            0
What industry do you work in?                                                                                                                                                                                                              81
Job title                                                                                                                                                                                                                                   2
If your job title needs additional context, please clarify here:                                                                                                                                                                        20896
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        0
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                           7356
Please indicate the currency                                                                                                                                                                                                                0
If "Other," please indicate the currency here:                                                                                                                                                                                          27963
If your income needs additional context, please provide it here:                                                                                                                                                                        25130
What country do you work in?                                                                                                                                                                                                                0
If you're in the U.S., what state do you work in?                                                                                                                                                                                        5056
What city do you work in?                                                                                                                                                                                                                  82
How many years of professional work experience do you have overall?                                                                                                                                                                         0
How many years of professional work experience do you have in your field?                                                                                                                                                                   0
What is your highest level of education completed?                                                                                                                                                                                        236
What is your gender?                                                                                                                                                                                                                      182
What is your race? (Choose all that apply.)                                                                                                                                                                                               190
dtype: int64

In [21]:
df = df.rename(columns={
    'Unnamed: 0': 'USERID',
    'Timestamp': 'Timestamp',
    'How old are you?': 'Age',
    'What industry do you work in?': 'Industry',
    'Job title': 'Job title',
    'If your job title needs additional context, please clarify here:': 'Job title context',
    'What is your annual salary? (You\'ll indicate the currency in a later question. If you are part-time or hourly, please estimate equivalent annual compensation.)': 'Annual Salary',
    'How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please indicate the currency.': 'Additional Compensation',
    'Please indicate the currency:': 'Currency',
    'If "Other," please indicate the currency here:': 'Other currency',
    'If your income needs additional context, please provide it here:': 'Salary context',
    'What country do you work in?': 'Country',
    'If you\\\'re in the U.S., what state do you work in?': 'State',
    'What city do you work in?': 'City',
    'How many years of professional work experience do you have overall?': 'Overall years of experience',
    'How many years of professional work experience do you have in your field?': 'Years of experience in current field',
    'What is your highest level of education completed?': 'Education level',
    'What is your gender?': 'Gender',
    'What is your race? (Choose all that apply.)': 'Race'
})

In [19]:
df.head()

,USERID,Timestamp,Age,Industry,Job title,Job title context,"What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:",Salary context,Country,"If you're in the U.S., what state do you work in?",City,Overall years of experience,Years of experience in current field,Education level,Gender,Race
0,0,2021-04-27 11:02:09.743,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,55000,0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,1,2021-04-27 11:02:21.562,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,54600,4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,2,2021-04-27 11:02:38.125,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,34000,NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,3,2021-04-27 11:02:40.643,25-34,Nonprofits,Program Manager,NaN,62000,3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4,2021-04-27 11:02:41.793,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,60000,7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

In [27]:
def missing_values(df):
  print('--Column and the number of missing values--')
  for column_name in df.columns:
    n_missing=df[column_name].isna().sum()
    print(f'{column_name}:{n_missing}')

print("column with missing value:")
print(missing_values(df))

column with missing value:
--Column and the number of missing values--
USERID:0
Timestamp:0
Age:0
Industry:81
Job title:2
Job title context:20896
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.):0
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.:7356
Please indicate the currency:0
If "Other," please indicate the currency here: :27963
Salary context:25130
Country:0
If you're in the U.S., what state do you work in?:5056
City:82
Overall years of experience:0
Years of experience in current field:0
Education level:236
Gender:182
Race:190
None

In [33]:
df.drop(['Job title context'],axis = 1)

df.head()

,USERID,Timestamp,Age,Industry,Job title,Job title context,"What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:",Salary context,Country,"If you're in the U.S., what state do you work in?",City,Overall years of experience,Years of experience in current field,Education level,Gender,Race
0,0,2021-04-27 11:02:09.743,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,55000,0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,1,2021-04-27 11:02:21.562,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,54600,4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,2,2021-04-27 11:02:38.125,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,34000,NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,3,2021-04-27 11:02:40.643,25-34,Nonprofits,Program Manager,NaN,62000,3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4,2021-04-27 11:02:41.793,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,60000,7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

In [41]:
rows_before = len(df)

In [42]:
print(f"Rows before: {rows_before}")
df = df.dropna()

Rows before: 28180

In [43]:
rows_after = len(df)

In [44]:
print(f"Rows after: {rows_after}")
print(f"Rows dropped:{rows_before-rows_after}")

Rows after: 4791
Rows dropped:23389

In [45]:
df.head()

,USERID,Timestamp,Age,Industry,Job title,Job title context,"What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,Country,"If you're in the U.S., what state do you work in?",City,Overall years of experience,Years of experience in current field,Education level,Gender,Race
8,8,2021-04-27 11:03:01.045,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,112000,10000.0,USD,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
35,35,2021-04-27 11:03:54.689,35-44,Education (Higher Education),Senior IRB Analyst,"State university, higher ed research adminstra...",68000,0.0,USD,USA,North Carolina,Research Triangle,5-7 years,2 - 4 years,Master's degree,Woman,White
38,38,2021-04-27 11:03:57.495,35-44,Government and Public Administration,Staff Services Manager II,"Mid-level manager, team of 13",78000,0.0,USD,USA,California,Sacramento,8 - 10 years,5-7 years,Master's degree,Woman,White
40,40,2021-04-27 11:04:01.323,45-54,Engineering or Manufacturing,Lead Engineer,supervisor level with no direct reports,100000,50000.0,USD,USA,Georgia,waynesboro,21 - 30 years,21 - 30 years,College degree,Woman,White
53,53,2021-04-27 11:04:19.348,35-44,Computing or Tech,Managed Services Sales Coordinator,Primarily proposal writing,72000,3000.0,USD,United States,Michigan,Troy,11 - 20 years,5-7 years,Master's degree,Woman,White

In [47]:
print("--columns and their unique items--")
for column in df.columns:
  n_unique = df[column].nunique()
  print(f'{column}:{n_unique}')

--columns and their unique items--
USERID:4791
Timestamp:4791
Age:7
Industry:312
Job title:3514
Job title context:4652
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.):1090
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.:349
Please indicate the currency:5
Country:61
If you're in the U.S., what state do you work in?:93
City:1433
Overall years of experience:8
Years of experience in current field:8
Education level:6
Gender:4
Race:35

In [49]:
print("\n--unique items in gender column--")
print(df['Gender'].unique())

--unique items in gender column--
['Woman' 'Non-binary' 'Man' 'Other or prefer not to answer']

In [50]:
df['Gender'] = df['Gender'].replace({
    'Woman': 'Female',
    'Man': 'Male',
    'Non-binary': 'Other',
    'Other or prefer not to answer':'Other',
    'Prefer not to answer': 'Other'

})

/tmp/ipython-input-1817716753.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender'] = df['Gender'].replace({

In [51]:
print('\n--gender values after replacement--')
print(df['Gender'].unique())

--gender values after replacement--
['Female' 'Other' 'Male']

In [58]:
import numpy as np
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(
    missing_values=np.nan,
    strategy='most_frequent',
    fill_value=None,
    copy=True,
    keep_empty_features=False,
    add_indicator=False
)

df_imputed = imputer.fit_transform(df)

In [60]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

# Create sample data
data = {
    'Age': [25, 30, np.nan, 35, 40, np.nan, 28],
    'Salary': [50000, np.nan, 70000, 80000, np.nan, 60000, 55000],
    'Experience': [2, 5, np.nan, 10, 3, 7, np.nan],
    'Department': ['IT', 'HR', 'IT', np.nan, 'Finance', 'IT', 'HR']
}

df = pd.DataFrame(data)

print("BEFORE IMPUTATION:")
print(df)
print("\nMissing values:")
print(df.isna().sum())

# --- Impute numerical columns ---
numerical_cols = ['Age', 'Salary', 'Experience']

# Impute using the mean strategy for numerical data
numerical_imputer = SimpleImputer(strategy='mean')
df[numerical_cols] = numerical_imputer.fit_transform(df[numerical_cols])

# --- Impute categorical columns ---
categorical_cols = ['Department']

# Impute using the most_frequent strategy for categorical data
categorical_imputer = SimpleImputer(strategy='most_frequent')

# Fit and transform the column
department_imputed = categorical_imputer.fit_transform(df[categorical_cols])

# Assign the imputed values back to the DataFrame
# Use .ravel() to convert the 2D array back to a 1D series for assignment
df['Department'] = department_imputed.ravel()

print("\n\nAFTER IMPUTATION:")
print(df)
print("\nMissing values:")
print(df.isna().sum())

BEFORE IMPUTATION:
    Age   Salary  Experience Department
0  25.0  50000.0         2.0         IT
1  30.0      NaN         5.0         HR
2   NaN  70000.0         NaN         IT
3  35.0  80000.0        10.0        NaN
4  40.0      NaN         3.0    Finance
5   NaN  60000.0         7.0         IT
6  28.0  55000.0         NaN         HR

Missing values:
Age           2
Salary        2
Experience    2
Department    1
dtype: int64


AFTER IMPUTATION:
    Age   Salary  Experience Department
0  25.0  50000.0         2.0         IT
1  30.0  63000.0         5.0         HR
2  31.6  70000.0         5.4         IT
3  35.0  80000.0        10.0         IT
4  40.0  63000.0         3.0    Finance
5  31.6  60000.0         7.0         IT
6  28.0  55000.0         5.4         HR

Missing values:
Age           0
Salary        0
Experience    0
Department    0
dtype: int64

In [61]:
import pandas as pd
import numpy as np
from scipy import stats

# 1. Create a sample DataFrame with 100 rows and 3 columns of random, normally distributed data
df = pd.DataFrame(np.random.randn(100, 3))

# 2. Filter the DataFrame to keep only non-outliers
# The condition keeps rows where the absolute Z-score for ALL columns is less than 3
df_cleaned = df[((np.abs(stats.zscore(df)) < 3).all(axis=1))]

# Print the shape (rows, columns) to show how many outliers were removed
print(f"Original shape: {df.shape}")
print(f"Cleaned shape: {df_cleaned.shape}")
print("\nFirst 5 rows of the cleaned DataFrame:")
print(df_cleaned.head())

Original shape: (100, 3)
Cleaned shape: (100, 3)

First 5 rows of the cleaned DataFrame:
          0         1         2
0  0.158392 -1.877870 -0.633108
1 -0.831978  0.443962 -0.872217
2 -1.399175 -0.731690  0.249394
3  0.089807  0.770258 -0.148533
4  2.253136 -0.766781 -0.863205

In [62]:
import pandas as pd
import numpy as np
from scipy import stats

# 1. Create a sample DataFrame with 100 rows and 3 columns of random, normally distributed data
df = pd.DataFrame(np.random.randn(100, 3))

# 2. Filter the DataFrame to keep only non-outliers
# The condition keeps rows where the absolute Z-score for ALL columns is less than 3
df_cleaned = df[((np.abs(stats.zscore(df)) < 3).all(axis=1))]

# Print the shape (rows, columns) to show how many outliers were removed
print(f"Original shape: {df.shape}")
print(f"Cleaned shape: {df_cleaned.shape}")
print("\nFirst 5 rows of the cleaned DataFrame:")
print(df_cleaned.head())

Original shape: (100, 3)
Cleaned shape: (100, 3)

First 5 rows of the cleaned DataFrame:
          0         1         2
0 -0.321909  2.143147  1.004899
1  0.666156  0.028551  0.978646
2 -1.767829 -1.517797 -0.362935
3  0.205183  0.068107 -0.266788
4 -0.287203 -0.212281  0.041336